name: 'setup-tfnotify'
description: 'Install kerraform/tfnotify in your workflow'
author: 'KeisukeYamashita'
inputs:
  tag: 
    required: false
    description: 'Which release to install'
    default: 'latest'
  token:
    required: false
    description: 'Credential to access to the repo to post the comment'
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'rss'
  color: 'purple'
